#![deny(improper_ctypes_definitions, improper_ctypes)]

use std::ffi::{CStr, c_char};
use std::path::Path;
use std::slice;

use tiny_skia::{Paint, PathBuilder, Pixmap, Rect, Stroke, Transform};

#[macro_use]
extern crate ffi_helpers;

mod canvas;
mod ffi;
mod ffi_element;
pub mod io;
pub mod text;

pub use ffi::{FfiArena, FfiError, FfiErrorCode, write_error_to_arena, write_panic_to_arena};
pub use ffi_element::{FfiElement, RectanglePayload, TextPayload};

// FFI results generated by macro
ffi_result!(FfiResultUnit, ());
ffi_result!(FfiResultCount, u32);

#[repr(C)]
pub struct FfiRectElement {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    /// Stroke width in pixels (0–255). `u8` is sufficient for any realistic overlay.
    /// The three bytes of C padding between this field and `outline_color_argb` are implicit
    /// (no explicit `_pad` field needed in Rust; Dart's `FfiRectElement` declares them explicitly).
    pub outline_thickness: u8,
    pub outline_color_argb: u32,
    pub shape_param: u32,
}

const _: () = assert!(std::mem::size_of::<FfiRectElement>() == 48);

#[repr(C)]
pub struct ByteBuffer {
    pub data: *mut u8,
    pub length: usize,
}

#[unsafe(no_mangle)]
/// # Safety
///
/// `ptr` must be a pointer previously returned by a Rust allocation function (e.g.
/// `Box::into_raw` on a boxed slice of length `len`), or null. Double-free is UB.
pub unsafe extern "C" fn frigate_free(ptr: *mut u8, len: usize) {
    null_pointer_check!(ptr);
    // SAFETY: Dart allocated this buffer via Rust `into_boxed_slice` → `Box::into_raw`.
    unsafe { drop(Vec::from_raw_parts(ptr, len, len)) };
}

/// Echo an FfiElement pointer back unchanged. Used by layout round-trip tests to verify the
/// Dart-side struct layout matches the Rust-side layout without any data transformation.
///
/// # Safety
///
/// `ptr` must be a valid, aligned pointer to a single `FfiElement` that lives at least
/// as long as the returned pointer is used.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ffi_echo_element(ptr: *const FfiElement) -> *const FfiElement {
    ptr
}

// Ported and renamed existing render_image to new API
ffi_export! {
    fn draw_elements(
        image_path_ptr: *const c_char,
        output_path_ptr: *const c_char,
        font_path_ptr: *const c_char,
        elements_ptr: *const FfiElement,
        elements_count: usize,
        image_quality: u8;
        arena: *mut FfiArena,
    ) -> FfiResultUnit {
        let image_path = unsafe { c_str_to_str(image_path_ptr, arena)? };
        let output_path = unsafe { c_str_to_str(output_path_ptr, arena)? };

        let elements: &[FfiElement] = if elements_count == 0 {
            &[]
        } else {
            if elements_ptr.is_null() {
                return Err(FfiError::new(FfiErrorCode::InvalidArg));
            }
            unsafe { slice::from_raw_parts(elements_ptr, elements_count) }
        };

        let arena_ref = unsafe { &*arena };
        let text_buffer: &[u8] = if arena_ref.text_len == 0 {
            &[]
        } else {
            if arena_ref.text_buf.is_null() {
                return Err(FfiError::new(FfiErrorCode::InvalidArg));
            }
            unsafe { slice::from_raw_parts(arena_ref.text_buf, arena_ref.text_len) }
        };

        let needs_font = elements.iter().any(|e| matches!(e, FfiElement::Text(_)));
        let font_bytes_holder;
        let font: Option<ab_glyph::FontRef<'_>> = if needs_font {
            if font_path_ptr.is_null() {
                return Err(write_error_to_arena(arena, FfiErrorCode::InvalidArg, "Missing font path"));
            }
            let font_path = unsafe { c_str_to_str(font_path_ptr, arena)? };
            font_bytes_holder = io::read_font(Path::new(font_path))
                .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Io, "Failed to read font"))?;
            Some(
                ab_glyph::FontRef::try_from_slice(&font_bytes_holder)
                    .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Font, "Failed to parse font"))?,
            )
        } else {
            None
        };

        let img = io::read_image(Path::new(image_path))
            .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Decode, "Failed to decode image"))?
            .into_rgba8();

        let mut surface = Surface::Rgba(img);

        for element in elements {
            match element {
                FfiElement::Rectangle(p) => {
                    let style: RectStyle = p.into();
                    if !style.paints_anything() {
                        continue;
                    }
                    draw_rect_on_pixmap(
                        surface.as_pixmap(),
                        p.x,
                        p.y,
                        p.width,
                        p.height,
                        &style,
                    );
                }
                FfiElement::Text(p) => {
                    let text_slice = element_text(p, text_buffer)
                        .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Utf8, "Invalid UTF-8 in text element"))?;
                    if let Some(font_ref) = &font {
                        draw_text_element(surface.as_rgba(), font_ref, p, text_slice);
                    }
                }
            }
        }

        let img = surface.into_rgba();
        io::write_image(Path::new(output_path), &img, image_quality)
            .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Encode, "Failed to encode image"))?;

        Ok(())
    }
}

unsafe fn c_str_to_str<'a>(ptr: *const c_char, arena: *mut FfiArena) -> Result<&'a str, FfiError> {
    if ptr.is_null() {
        return Err(FfiError::new(FfiErrorCode::InvalidArg));
    }
    unsafe { CStr::from_ptr(ptr) }
        .to_str()
        .map_err(|_| write_error_to_arena(arena, FfiErrorCode::Utf8, "Invalid UTF-8 in path"))
}

fn element_text<'b>(p: &TextPayload, text_buffer: &'b [u8]) -> Result<&'b str, ()> {
    let start = p.text_offset as usize;
    let len = p.text_len as usize;
    let end = start.checked_add(len).ok_or(())?;
    if end > text_buffer.len() {
        return Err(());
    }
    std::str::from_utf8(&text_buffer[start..end]).map_err(|_| ())
}

enum Surface {
    Rgba(image::RgbaImage),
    Pixmap(Pixmap),
}

impl Surface {
    fn as_rgba(&mut self) -> &mut image::RgbaImage {
        if let Self::Pixmap(p) = self {
            *self = Self::Rgba(canvas::from_pixmap(p));
        }
        match self {
            Self::Rgba(img) => img,
            Self::Pixmap(_) => unreachable!(),
        }
    }

    fn as_pixmap(&mut self) -> &mut Pixmap {
        if let Self::Rgba(img) = self {
            *self = Self::Pixmap(canvas::to_pixmap(img));
        }
        match self {
            Self::Pixmap(p) => p,
            Self::Rgba(_) => unreachable!(),
        }
    }

    fn into_rgba(self) -> image::RgbaImage {
        match self {
            Self::Rgba(img) => img,
            Self::Pixmap(p) => canvas::from_pixmap(&p),
        }
    }
}

fn draw_text_element(
    img: &mut image::RgbaImage,
    font: &ab_glyph::FontRef<'_>,
    p: &TextPayload,
    text_str: &str,
) {
    let params = text::TextParams {
        text: text_str,
        x: p.x as f32,
        y: p.y as f32,
        font_size_px: p.height as f32,
        rotation_rad: (p.rotation_deg as f32).to_radians(),
        color: argb_to_rgba(p.fill_color_argb),
    };
    text::render_text_overlay(img, font, &params);
}

#[inline]
fn argb_unpack(argb: u32) -> [u8; 4] {
    [
        ((argb >> 16) & 0xFF) as u8,
        ((argb >> 8) & 0xFF) as u8,
        (argb & 0xFF) as u8,
        ((argb >> 24) & 0xFF) as u8,
    ]
}

fn argb_to_rgba(argb: u32) -> image::Rgba<u8> {
    image::Rgba(argb_unpack(argb))
}

#[inline]
fn argb_alpha(argb: u32) -> u8 {
    ((argb >> 24) & 0xFF) as u8
}

pub(crate) struct RectStyle {
    pub(crate) outline_thickness: u32,
    pub(crate) outline_color_argb: u32,
    pub(crate) fill_color_argb: u32,
    pub(crate) corner_radius_px: u32,
}

impl RectStyle {
    pub(crate) fn paints_anything(&self) -> bool {
        let has_outline = self.outline_thickness > 0 && argb_alpha(self.outline_color_argb) > 0;
        let has_fill = argb_alpha(self.fill_color_argb) > 0;
        has_outline || has_fill
    }
}

impl From<&RectanglePayload> for RectStyle {
    fn from(p: &RectanglePayload) -> Self {
        Self {
            outline_thickness: p.outline_thickness as u32,
            outline_color_argb: p.outline_color_argb,
            fill_color_argb: p.fill_color_argb,
            corner_radius_px: p.corner_radius as u32,
        }
    }
}

impl From<&FfiRectElement> for RectStyle {
    fn from(r: &FfiRectElement) -> Self {
        Self {
            outline_thickness: r.outline_thickness as u32,
            outline_color_argb: r.outline_color_argb,
            fill_color_argb: 0,
            corner_radius_px: r.shape_param,
        }
    }
}

fn draw_rect_on_pixmap(
    pixmap: &mut Pixmap,
    x: f64,
    y: f64,
    width: f64,
    height: f64,
    style: &RectStyle,
) {
    if width <= 0.0 || height <= 0.0 || !x.is_finite() || !y.is_finite() {
        return;
    }

    let rect = Rect::from_xywh(x as f32, y as f32, width as f32, height as f32);
    let Some(rect) = rect else { return };

    let mut paint = Paint::default();
    if argb_alpha(style.fill_color_argb) > 0 {
        let [r, g, b, a] = argb_unpack(style.fill_color_argb);
        paint.set_color_rgba8(r, g, b, a);

        if style.corner_radius_px > 0 {
            let path = build_rect_path(x, y, width, height, style.corner_radius_px);
            pixmap.fill_path(
                &path,
                &paint,
                tiny_skia::FillRule::Winding,
                Transform::identity(),
                None,
            );
        } else {
            pixmap.fill_rect(rect, &paint, Transform::identity(), None);
        }
    }

    if style.outline_thickness > 0 && argb_alpha(style.outline_color_argb) > 0 {
        let [r, g, b, a] = argb_unpack(style.outline_color_argb);
        paint.set_color_rgba8(r, g, b, a);
        let stroke = Stroke { width: style.outline_thickness.min(width.min(height) as u32) as f32, ..Stroke::default() };

        if style.corner_radius_px > 0 {
            let path = build_rect_path(x, y, width, height, style.corner_radius_px);
            pixmap.stroke_path(&path, &paint, &stroke, Transform::identity(), None);
        } else if let Some(path) = build_sharp_rect_path(x, y, width, height) {
            pixmap.stroke_path(&path, &paint, &stroke, Transform::identity(), None);
        }
    }
}

fn build_rect_path(x: f64, y: f64, w: f64, h: f64, r: u32) -> tiny_skia::Path {
    let (x, y, w, h) = (x as f32, y as f32, w as f32, h as f32);
    let r = (r as f32).min(w / 2.0).min(h / 2.0);

    let mut pb = PathBuilder::new();
    pb.move_to(x + r, y);
    pb.line_to(x + w - r, y);
    pb.quad_to(x + w, y, x + w, y + r);
    pb.line_to(x + w, y + h - r);
    pb.quad_to(x + w, y + h, x + w - r, y + h);
    pb.line_to(x + r, y + h);
    pb.quad_to(x, y + h, x, y + h - r);
    pb.line_to(x, y + r);
    pb.quad_to(x, y, x + r, y);
    pb.close();
    pb.finish().unwrap()
}

/// Build a plain rectangle path (4 line segments, no rounding).
/// `tiny_skia` 0.12 removed `Pixmap::stroke_rect`; use `stroke_path` with this helper.
fn build_sharp_rect_path(x: f64, y: f64, w: f64, h: f64) -> Option<tiny_skia::Path> {
    let (x, y, w, h) = (x as f32, y as f32, w as f32, h as f32);
    let mut pb = PathBuilder::new();
    pb.move_to(x, y);
    pb.line_to(x + w, y);
    pb.line_to(x + w, y + h);
    pb.line_to(x, y + h);
    pb.close();
    pb.finish()
}

fn is_positive_finite(v: f64) -> bool {
    v.is_finite() && v > 0.0
}

pub fn draw_rect_element(img: &mut image::RgbaImage, e: &FfiElement) {
    if let FfiElement::Rectangle(p) = e {
        if !is_positive_finite(p.width) || !is_positive_finite(p.height) {
            return;
        }
        let style: RectStyle = p.into();
        if !style.paints_anything() {
            return;
        }
        let mut pixmap = canvas::to_pixmap(img);
        draw_rect_on_pixmap(&mut pixmap, p.x, p.y, p.width, p.height, &style);
        *img = canvas::from_pixmap(&pixmap);
    }
}
