#![deny(improper_ctypes_definitions, improper_ctypes)]

use std::ffi::{CStr, c_char};
use std::path::Path;
use std::slice;

use tiny_skia::{Paint, PathBuilder, Pixmap, Rect, Stroke, Transform};

mod canvas;
mod ffi;
mod ffi_element;
pub mod io;
pub mod text;

pub use ffi::{FfiArena, FfiError, FfiErrorCode, write_error_to_arena, write_panic_to_arena};
pub use ffi_element::{FfiElement, RectanglePayload, TextPayload};

// FFI results generated by macro
ffi_result!(FfiResultUnit, ());
ffi_result!(FfiResultCount, u32);

// Rust-side layout anchors: if these ever change, the Dart Struct declarations must be updated.
// `repr(C, u8)` enum layout: discriminant(u8) + implicit_pad + payload_union → sizes below.
const _: () = assert!(std::mem::size_of::<FfiResultUnit>() == 6);
const _: () = assert!(std::mem::size_of::<FfiResultCount>() == 8);

#[repr(C)]
pub struct FfiRectElement {
    pub x: f64,
    pub y: f64,
    pub width: f64,
    pub height: f64,
    /// Stroke width in pixels (0–255). `u8` is sufficient for any realistic overlay.
    /// The three bytes of C padding between this field and `outline_color_argb` are implicit
    /// (no explicit `_pad` field needed in Rust; Dart's `FfiRectElement` declares them explicitly).
    pub outline_thickness: u8,
    pub outline_color_argb: u32,
    pub shape_param: u32,
}

const _: () = assert!(std::mem::size_of::<FfiRectElement>() == 48);

#[repr(C)]
pub struct ByteBuffer {
    pub data: *mut u8,
    pub length: usize,
}

/// Bytes-in / bytes-out export: composites [rects_count] rectangles over a PNG/JPEG image and
/// returns the result as a JPEG byte buffer owned by Rust.
///
/// Returns a [ByteBuffer] with `data == null` on panic (catch_unwind boundary).
/// Caller must free the returned buffer with [free_bytes].
///
/// # Safety
///
/// `img_ptr` must point to `img_len` valid bytes of image data.
/// `rects_ptr` must point to `rects_count` valid `FfiRectElement` values (or be null when
/// `rects_count == 0`).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn export_image(
    img_ptr: *const u8,
    img_len: usize,
    rects_ptr: *const FfiRectElement,
    rects_count: usize,
    image_quality: u8,
) -> ByteBuffer {
    let img_bytes: &[u8] = if img_len == 0 {
        &[]
    } else {
        if img_ptr.is_null() {
            return ByteBuffer {
                data: std::ptr::null_mut(),
                length: 0,
            };
        }
        unsafe { slice::from_raw_parts(img_ptr, img_len) }
    };
    // Handle empty case explicitly — `slice::from_raw_parts` requires non-null even for len == 0.
    let rects: &[FfiRectElement] = if rects_count == 0 {
        &[]
    } else {
        unsafe { slice::from_raw_parts(rects_ptr, rects_count) }
    };
    // Panicking across an FFI boundary is undefined behavior; errors return a null ByteBuffer.
    match std::panic::catch_unwind(|| render_jpeg_with_rects(img_bytes, rects, image_quality)) {
        Ok(Ok(bytes)) => {
            // into_boxed_slice shrinks capacity to == len so free_bytes can reconstruct safely.
            let boxed = bytes.into_boxed_slice();
            let length = boxed.len();
            ByteBuffer {
                data: Box::into_raw(boxed) as *mut u8,
                length,
            }
        }
        Ok(Err(_)) | Err(_) => ByteBuffer {
            data: std::ptr::null_mut(),
            length: 0,
        },
    }
}

/// Free a Rust-allocated byte buffer (returned by [export_image]). Null-safe.
///
/// `isLeaf: true` — never calls back into Dart, so the Dart VM can skip the safepoint preamble.
///
/// # Safety
///
/// `ptr` must have been returned by `export_image` (and not yet freed); `len` must match.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn free_bytes(ptr: *mut u8, len: usize) {
    if ptr.is_null() {
        return;
    }
    // SAFETY: ptr came from export_image → into_boxed_slice → Box::into_raw; capacity == len.
    unsafe { drop(Vec::from_raw_parts(ptr, len, len)) };
}

/// Echo an FfiElement pointer back unchanged. Only compiled in debug builds — its only purpose
/// is layout round-trip tests. The Rust symbol must not be present in release `.dylib`s.
///
/// # Safety
///
/// `ptr` must be a valid, aligned pointer to a single `FfiElement` that lives at least
/// as long as the returned pointer is used.
#[cfg(any(test, feature = "ffi-echo"))]
#[unsafe(no_mangle)]
pub unsafe extern "C" fn ffi_echo_element(ptr: *const FfiElement) -> *const FfiElement {
    ptr
}

/// Unified render call: reads the image from `image_path_ptr`, composites all `FfiElement`s
/// (rectangles, text, future shapes), writes the result to `output_path_ptr`.
///
/// Returns `void`; result is written to `*out`. Using an out-pointer avoids struct-return ABI
/// differences between SysV x86-64, Win64, AArch64 AAPCS and ARMv7 for the 6-byte result type.
///
/// # Safety
///
/// All pointer arguments must be valid for the duration of the call. `arena` and `out` must
/// be non-null. `elements_ptr` may be null only when `elements_count == 0`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn draw_elements(
    image_path_ptr: *const c_char,
    output_path_ptr: *const c_char,
    font_path_ptr: *const c_char,
    elements_ptr: *const FfiElement,
    elements_count: usize,
    image_quality: u8,
    arena: *mut FfiArena,
    out: *mut FfiResultUnit,
) {
    if out.is_null() {
        return;
    }
    let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        let inner: Result<_, FfiError> = (|| {
            if arena.is_null() {
                return Err(FfiError::new(FfiErrorCode::InvalidArg));
            }
            let image_path = unsafe { c_str_to_str(image_path_ptr, arena)? };
            let output_path = unsafe { c_str_to_str(output_path_ptr, arena)? };

            let elements: &[FfiElement] = if elements_count == 0 {
                &[]
            } else {
                if elements_ptr.is_null() {
                    return Err(FfiError::new(FfiErrorCode::InvalidArg));
                }
                unsafe { slice::from_raw_parts(elements_ptr, elements_count) }
            };

            let arena_ref = unsafe { &*arena };
            // SAFETY: arena is non-null (checked above). Copy text buffer scalars into local
            // variables so `arena_ref` can be dropped before any `write_error_to_arena` call
            // creates `&mut *arena` — having both alive simultaneously would violate Rust's
            // aliasing rules.
            let (text_buf_ptr, text_buf_len) = (arena_ref.text_buf, arena_ref.text_len);
            let _ = arena_ref;
            let text_buffer: &[u8] = if text_buf_len == 0 {
                &[]
            } else {
                if text_buf_ptr.is_null() {
                    return Err(FfiError::new(FfiErrorCode::InvalidArg));
                }
                unsafe { slice::from_raw_parts(text_buf_ptr, text_buf_len) }
            };

            let needs_font = elements.iter().any(|e| matches!(e, FfiElement::Text(_)));
            let font_bytes_holder;
            let font: Option<ab_glyph::FontRef<'_>> = if needs_font {
                if font_path_ptr.is_null() {
                    // SAFETY: arena is non-null (checked above).
                    return Err(unsafe {
                        write_error_to_arena(arena, FfiErrorCode::InvalidArg, "Missing font path")
                    });
                }
                let font_path = unsafe { c_str_to_str(font_path_ptr, arena)? };
                font_bytes_holder = io::read_font(Path::new(font_path)).map_err(|_| unsafe {
                    write_error_to_arena(arena, FfiErrorCode::Io, "Failed to read font")
                })?;
                Some(
                    ab_glyph::FontRef::try_from_slice(&font_bytes_holder).map_err(|_| unsafe {
                        write_error_to_arena(arena, FfiErrorCode::Font, "Failed to parse font")
                    })?,
                )
            } else {
                None
            };

            let img = io::read_image(Path::new(image_path))
                .map_err(|_| unsafe {
                    write_error_to_arena(arena, FfiErrorCode::Decode, "Failed to decode image")
                })?
                .into_rgba8();

            let mut surface = Surface::Rgba(img);

            for element in elements {
                match element {
                    FfiElement::Rectangle(p) => {
                        let style: RectStyle = p.into();
                        if !style.paints_anything() {
                            continue;
                        }
                        draw_rect_on_pixmap(
                            surface.as_pixmap(),
                            p.x,
                            p.y,
                            p.width,
                            p.height,
                            &style,
                        );
                    }
                    FfiElement::Text(p) => {
                        let text_slice = element_text(p, text_buffer).map_err(|e| unsafe {
                            match e {
                                ElementTextError::Bounds => write_error_to_arena(
                                    arena,
                                    FfiErrorCode::InvalidArg,
                                    "Text element slice out of bounds",
                                ),
                                ElementTextError::Utf8 => write_error_to_arena(
                                    arena,
                                    FfiErrorCode::Utf8,
                                    "Invalid UTF-8 in text element",
                                ),
                            }
                        })?;
                        if let Some(font_ref) = &font {
                            draw_text_element(surface.as_rgba(), font_ref, p, text_slice);
                        }
                    }
                }
            }

            let img = surface.into_rgba();
            io::write_image(Path::new(output_path), &img, image_quality).map_err(|_| unsafe {
                write_error_to_arena(arena, FfiErrorCode::Encode, "Failed to encode image")
            })?;

            Ok(())
        })();
        inner
    }));

    let ffi_result = match result {
        Ok(Ok(v)) => FfiResultUnit::ok(v),
        Ok(Err(e)) => FfiResultUnit::err(e),
        Err(payload) => {
            let msg = if let Some(s) = payload.downcast_ref::<&'static str>() {
                (*s).to_string()
            } else if let Some(s) = payload.downcast_ref::<String>() {
                s.clone()
            } else {
                "panic with non-string payload".to_string()
            };
            // SAFETY: arena was validated non-null before any code that could panic runs.
            let err = unsafe { write_panic_to_arena(arena, &msg) };
            FfiResultUnit::err(err)
        }
    };
    // SAFETY: `out` is non-null and writable for the duration of this call.
    unsafe { out.write(ffi_result) };
}

unsafe fn c_str_to_str<'a>(ptr: *const c_char, arena: *mut FfiArena) -> Result<&'a str, FfiError> {
    if ptr.is_null() {
        return Err(FfiError::new(FfiErrorCode::InvalidArg));
    }
    unsafe { CStr::from_ptr(ptr) }.to_str().map_err(|_| unsafe {
        write_error_to_arena(arena, FfiErrorCode::Utf8, "Invalid UTF-8 in path")
    })
}

#[derive(Debug)]
enum ElementTextError {
    /// The slice bounds are out of range — maps to `FfiErrorCode::InvalidArg`.
    Bounds,
    /// The bytes are not valid UTF-8 — maps to `FfiErrorCode::Utf8`.
    Utf8,
}

fn element_text<'b>(p: &TextPayload, text_buffer: &'b [u8]) -> Result<&'b str, ElementTextError> {
    let start = p.text_offset as usize;
    let len = p.text_len as usize;
    let end = start.checked_add(len).ok_or(ElementTextError::Bounds)?;
    if end > text_buffer.len() {
        return Err(ElementTextError::Bounds);
    }
    std::str::from_utf8(&text_buffer[start..end]).map_err(|_| ElementTextError::Utf8)
}

fn render_jpeg_with_rects(
    img_bytes: &[u8],
    rects: &[FfiRectElement],
    image_quality: u8,
) -> Result<Vec<u8>, io::IoError> {
    let img = image::load_from_memory(img_bytes)
        .map_err(|_| io::IoError::Decode)?
        .into_rgba8();
    // One pixmap conversion pair for all rects — cheaper than per-rect round-trips.
    let mut pixmap = canvas::to_pixmap(&img);
    for r in rects {
        draw_rect_on_pixmap(&mut pixmap, r.x, r.y, r.width, r.height, &r.into());
    }
    let img = canvas::from_pixmap(&pixmap);
    let rgb_img = image::DynamicImage::ImageRgba8(img).into_rgb8();
    let mut buf = std::io::Cursor::new(Vec::new());
    image::codecs::jpeg::JpegEncoder::new_with_quality(&mut buf, image_quality)
        .encode_image(&rgb_img)
        .map_err(|_| io::IoError::Encode)?;
    Ok(buf.into_inner())
}

enum Surface {
    Rgba(image::RgbaImage),
    Pixmap(Pixmap),
}

impl Surface {
    fn as_rgba(&mut self) -> &mut image::RgbaImage {
        if let Self::Pixmap(p) = self {
            *self = Self::Rgba(canvas::from_pixmap(p));
        }
        match self {
            Self::Rgba(img) => img,
            Self::Pixmap(_) => unreachable!(),
        }
    }

    fn as_pixmap(&mut self) -> &mut Pixmap {
        if let Self::Rgba(img) = self {
            *self = Self::Pixmap(canvas::to_pixmap(img));
        }
        match self {
            Self::Pixmap(p) => p,
            Self::Rgba(_) => unreachable!(),
        }
    }

    fn into_rgba(self) -> image::RgbaImage {
        match self {
            Self::Rgba(img) => img,
            Self::Pixmap(p) => canvas::from_pixmap(&p),
        }
    }
}

fn draw_text_element(
    img: &mut image::RgbaImage,
    font: &ab_glyph::FontRef<'_>,
    p: &TextPayload,
    text_str: &str,
) {
    let params = text::TextParams {
        text: text_str,
        x: p.x as f32,
        y: p.y as f32,
        font_size_px: p.height as f32,
        rotation_rad: (p.rotation_deg as f32).to_radians(),
        color: argb_to_rgba(p.fill_color_argb),
    };
    text::render_text_overlay(img, font, &params);
}

#[inline]
fn argb_unpack(argb: u32) -> [u8; 4] {
    [
        ((argb >> 16) & 0xFF) as u8,
        ((argb >> 8) & 0xFF) as u8,
        (argb & 0xFF) as u8,
        ((argb >> 24) & 0xFF) as u8,
    ]
}

#[inline]
fn argb_to_tiny_color(argb: u32) -> tiny_skia::Color {
    let [r, g, b, a] = argb_unpack(argb);
    tiny_skia::Color::from_rgba8(r, g, b, a)
}

fn argb_to_rgba(argb: u32) -> image::Rgba<u8> {
    image::Rgba(argb_unpack(argb))
}

#[inline]
fn argb_alpha(argb: u32) -> u8 {
    ((argb >> 24) & 0xFF) as u8
}

pub(crate) struct RectStyle {
    pub(crate) outline_thickness: u8,
    pub(crate) outline_color_argb: u32,
    pub(crate) fill_color_argb: u32,
    pub(crate) corner_radius_px: u32,
}

impl RectStyle {
    pub(crate) fn paints_anything(&self) -> bool {
        let has_outline = self.outline_thickness > 0 && argb_alpha(self.outline_color_argb) > 0;
        let has_fill = argb_alpha(self.fill_color_argb) > 0;
        has_outline || has_fill
    }
}

impl From<&RectanglePayload> for RectStyle {
    fn from(p: &RectanglePayload) -> Self {
        Self {
            outline_thickness: p.outline_thickness,
            outline_color_argb: p.outline_color_argb,
            fill_color_argb: p.fill_color_argb,
            corner_radius_px: p.corner_radius as u32,
        }
    }
}

impl From<&FfiRectElement> for RectStyle {
    fn from(r: &FfiRectElement) -> Self {
        Self {
            outline_thickness: r.outline_thickness,
            outline_color_argb: r.outline_color_argb,
            // `export_image` is an outline-only path — fill is always transparent.
            fill_color_argb: 0,
            corner_radius_px: r.shape_param,
        }
    }
}

fn draw_rect_on_pixmap(
    pixmap: &mut Pixmap,
    x: f64,
    y: f64,
    width: f64,
    height: f64,
    style: &RectStyle,
) {
    if width <= 0.0 || height <= 0.0 || !x.is_finite() || !y.is_finite() {
        return;
    }
    let Some(rect) = Rect::from_xywh(x as f32, y as f32, width as f32, height as f32) else {
        return;
    };
    let path = build_rect_path(rect, style.corner_radius_px);
    let anti_alias = style.corner_radius_px > 0;

    if argb_alpha(style.fill_color_argb) > 0 {
        let mut paint = Paint::default();
        paint.set_color(argb_to_tiny_color(style.fill_color_argb));
        paint.anti_alias = anti_alias;
        pixmap.fill_path(
            &path,
            &paint,
            tiny_skia::FillRule::Winding,
            Transform::identity(),
            None,
        );
    }

    if style.outline_thickness > 0 && argb_alpha(style.outline_color_argb) > 0 {
        let max_stroke = rect.width().min(rect.height());
        let stroke_width = (style.outline_thickness as f32).min(max_stroke);
        if stroke_width > 0.0 {
            let mut paint = Paint::default();
            paint.set_color(argb_to_tiny_color(style.outline_color_argb));
            paint.anti_alias = anti_alias;
            let stroke = Stroke {
                width: stroke_width,
                ..Stroke::default()
            };
            pixmap.stroke_path(&path, &paint, &stroke, Transform::identity(), None);
        }
    }
}

fn build_rect_path(rect: Rect, corner_radius_px: u32) -> tiny_skia::Path {
    if corner_radius_px == 0 {
        return PathBuilder::from_rect(rect);
    }
    let max_r = rect.width().min(rect.height()) * 0.5;
    let r = (corner_radius_px as f32).min(max_r);
    if r <= 0.0 {
        return PathBuilder::from_rect(rect);
    }
    const KAPPA: f32 = 0.552_284_8;
    let c = r * KAPPA;

    let l = rect.left();
    let t = rect.top();
    let ri = rect.right();
    let b = rect.bottom();

    let mut pb = PathBuilder::new();
    pb.move_to(l + r, t);
    pb.line_to(ri - r, t);
    pb.cubic_to(ri - r + c, t, ri, t + r - c, ri, t + r);
    pb.line_to(ri, b - r);
    pb.cubic_to(ri, b - r + c, ri - r + c, b, ri - r, b);
    pb.line_to(l + r, b);
    pb.cubic_to(l + r - c, b, l, b - r + c, l, b - r);
    pb.line_to(l, t + r);
    pb.cubic_to(l, t + r - c, l + r - c, t, l + r, t);
    pb.close();
    pb.finish().unwrap()
}

fn is_positive_finite(v: f64) -> bool {
    v.is_finite() && v > 0.0
}

pub fn draw_rect_element(img: &mut image::RgbaImage, e: &FfiElement) {
    if let FfiElement::Rectangle(p) = e {
        if !is_positive_finite(p.width) || !is_positive_finite(p.height) {
            return;
        }
        let style: RectStyle = p.into();
        if !style.paints_anything() {
            return;
        }
        let mut pixmap = canvas::to_pixmap(img);
        draw_rect_on_pixmap(&mut pixmap, p.x, p.y, p.width, p.height, &style);
        *img = canvas::from_pixmap(&pixmap);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn tiny_red_png() -> Vec<u8> {
        use image::{ImageEncoder, RgbaImage};
        let img = RgbaImage::from_pixel(4, 4, image::Rgba([255, 0, 0, 255]));
        let mut buf = std::io::Cursor::new(Vec::new());
        image::codecs::png::PngEncoder::new(&mut buf)
            .write_image(img.as_raw(), 4, 4, image::ExtendedColorType::Rgba8)
            .unwrap();
        buf.into_inner()
    }

    // ── render_jpeg_with_rects ───────────────────────────────────────────────────────────────────

    #[test]
    fn render_no_rects_returns_valid_jpeg() {
        let jpeg = render_jpeg_with_rects(&tiny_red_png(), &[], 80).unwrap();
        assert!(jpeg.len() > 2);
        assert_eq!(&jpeg[..2], &[0xFF, 0xD8], "must start with JPEG SOI marker");
    }

    #[test]
    fn render_with_outline_rect_returns_valid_jpeg() {
        let rect = FfiRectElement {
            x: 0.0,
            y: 0.0,
            width: 4.0,
            height: 4.0,
            outline_thickness: 1,
            outline_color_argb: 0xFF_00_FF_00,
            shape_param: 0,
        };
        let jpeg = render_jpeg_with_rects(&tiny_red_png(), &[rect], 90).unwrap();
        assert_eq!(&jpeg[..2], &[0xFF, 0xD8]);
    }

    #[test]
    fn render_with_zero_thickness_differs_from_with_outline() {
        // A visible outline must change the JPEG bytes versus no outline (thickness=0).
        let png = tiny_red_png();
        let no_outline = FfiRectElement {
            x: 0.0,
            y: 0.0,
            width: 4.0,
            height: 4.0,
            outline_thickness: 0,
            outline_color_argb: 0xFF_00_FF_00,
            shape_param: 0,
        };
        let with_outline = FfiRectElement {
            outline_thickness: 2,
            ..no_outline
        };
        let a = render_jpeg_with_rects(&png, &[no_outline], 90).unwrap();
        let b = render_jpeg_with_rects(&png, &[with_outline], 90).unwrap();
        assert_ne!(a, b, "visible outline must change the JPEG output");
    }

    #[test]
    fn render_quality_zero_and_max_both_produce_jpeg() {
        let png = tiny_red_png();
        for q in [0u8, 255] {
            let jpeg = render_jpeg_with_rects(&png, &[], q).unwrap();
            assert_eq!(
                &jpeg[..2],
                &[0xFF, 0xD8],
                "quality={q} must yield a valid JPEG"
            );
        }
    }

    #[test]
    fn render_corrupt_bytes_returns_decode_error() {
        // render_jpeg_with_rects returns Err on corrupt input instead of panicking.
        // export_image wraps it in catch_unwind as an extra safety net, but the primary
        // contract is Result — no panic cross the FFI boundary even with panic=abort.
        let result = render_jpeg_with_rects(&[0xDE, 0xAD, 0xBE, 0xEF], &[], 80);
        assert!(result.is_err(), "corrupt input must return Err, not panic");
    }
}

#[cfg(test)]
mod element_text_tests {
    use super::*;

    fn make_text_payload(text_offset: u32, text_len: u32) -> TextPayload {
        TextPayload {
            x: 0.0,
            y: 0.0,
            height: 16.0,
            rotation_deg: 0,
            fill_color_argb: 0xFF_00_00_00,
            blur: 0,
            _pad: [0; 3],
            font_id: 0,
            text_offset,
            text_len,
        }
    }

    #[test]
    fn happy_path_returns_correct_slice() {
        let buf = b"hello world";
        let p = make_text_payload(6, 5); // "world"
        assert_eq!(element_text(&p, buf).unwrap(), "world");
    }

    #[test]
    fn full_buffer_returns_whole_string() {
        let buf = b"abc";
        let p = make_text_payload(0, 3);
        assert_eq!(element_text(&p, buf).unwrap(), "abc");
    }

    #[test]
    fn zero_length_returns_empty_str() {
        let buf = b"ignored";
        let p = make_text_payload(0, 0);
        assert_eq!(element_text(&p, buf).unwrap(), "");
    }

    #[test]
    fn end_beyond_buffer_returns_bounds_error() {
        let buf = b"hi";
        // end = 1 + 5 = 6 > 2 → Bounds
        let p = make_text_payload(1, 5);
        assert!(matches!(
            element_text(&p, buf),
            Err(ElementTextError::Bounds)
        ));
    }

    #[test]
    fn offset_beyond_buffer_returns_bounds_error() {
        let buf = b"x";
        // start = u32::MAX → start alone exceeds buf.len() when added to any len
        let p = make_text_payload(u32::MAX, 0);
        assert!(matches!(
            element_text(&p, buf),
            Err(ElementTextError::Bounds)
        ));
    }

    #[test]
    fn invalid_utf8_returns_utf8_error() {
        // 0xFF is never valid in UTF-8.
        let buf: &[u8] = &[0xFF, 0xFE];
        let p = make_text_payload(0, 2);
        assert!(matches!(element_text(&p, buf), Err(ElementTextError::Utf8)));
    }
}

#[cfg(test)]
mod draw_elements_tests {
    use super::*;

    #[test]
    fn null_out_is_silent_noop() {
        // Passing a null `out` pointer must be a silent no-op — no panic, no write to *out.
        // This guards the defensive null-check added to prevent UB on a misuse path.
        let mut error_buf = [0u8; 256];
        let mut arena = FfiArena {
            text_buf: std::ptr::null(),
            text_len: 0,
            image_buf: std::ptr::null(),
            image_len: 0,
            error_buf: error_buf.as_mut_ptr(),
            error_cap: error_buf.len(),
        };
        unsafe {
            draw_elements(
                std::ptr::null(),
                std::ptr::null(),
                std::ptr::null(),
                std::ptr::null(),
                0,
                90,
                &mut arena,
                std::ptr::null_mut(), // out = null → must return immediately
            );
        }
        // Reaching here without panicking confirms the null-out guard works.
    }
}
