version: 0.0.1
name: frigatebird
description: "Demonstrates how to use the frigate_draw package."
publish_to: none


environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  frigate_draw:
    path: ../
  meta: any

dev_dependencies:
  dart_code_metrics_presets: ^2.30.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/sample.png
