version: 0.0.1
name: frigatebird
description: "Pure Dart FFI core for geometric image annotation with Rust-powered export."
repository: https://github.com/tsinis/frigate_draw/tree/main/frigatebird

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  ffi: ^2.2.0
  hooks: ^2.0.2 # Blocked by native_toolchain_rust.
  meta: ^1.18.0 # Constrained by latest stable Flutter SDK.
  native_toolchain_rust: ^1.0.4+0

dev_dependencies:
  benchmark_harness: ^2.4.0
  crypto: ^3.0.7
  dart_code_metrics_presets: any # Constrained in the workspace pubspec.yaml
  lints: ^6.1.0
  test: any # Constrained in the workspace pubspec.yaml
