version: 2
enable-beta-ecosystems: true
updates:
  # Maintain dependencies for Rust
  - package-ecosystem: "cargo"
    directory: "/frigatebird/rust"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "rust"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "github_actions"
    open-pull-requests-limit: 10

  # Maintain dependencies for Dart packages
  - package-ecosystem: "pub"
    versioning-strategy: increase
    directories:
      - "/frigatebird"
      - "/frigatedraw"
      - "/frigatedraw/example"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "dart"
    open-pull-requests-limit: 5

  # Maintain dependencies for Android example
  - package-ecosystem: "gradle"
    directory: "/frigatedraw/example/android"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "Europe/Vienna"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 5
