version: 0.0.1
name: frigate_draw
description: "Geometric-first image editor/annotation canvas"

environment:
  sdk: ^3.11.4

dependencies:
  ffi: ^2.2.0 # For FFI bindings and memory management.
  flutter:
    sdk: flutter
  hooks: ^1.0.2 # For hook/build.dart integration (transitive dependency of native_toolchain_rust).
  native_toolchain_rust: ^1.0.3  # For hook/build.dart integration.

dev_dependencies:
  benchmark_harness: ^2.4.0
  dart_code_metrics_presets: ^2.30.0
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  lints: any
  test: any
