name: frigate
description: Workspace for frigate ecosystem
publish_to: none
maintainer: Roman Cinis
repository: https://github.com/tsinis/frigate
issue_tracker: https://github.com/tsinis/frigate/issues
homepage: https://tsin.is/frigate/
topics:
  - draw
  - image
  - imageproc
  - annotation
  - rust

environment:
  sdk: ^3.11.4

workspace:
  - frigatebird
  - frigatedraw
  - frigatedraw/example

dev_dependencies:
  benchmark_harness: ^2.4.0 # From Google. Defines top level dependency constraint.
  coverage: ^1.15.0 # From Google. Defines top level dependency constraint.
  dart_code_metrics_presets: ^2.30.0 # DCM. Defines top level dependency constraint.
  lints: ^6.1.0 # From Google. Defines top level dependency constraint.
  test: ^1.30.0 # From Google. Defines top level dependency constraint.
