[advisories]
ignore = [
    "RUSTSEC-2025-0140", # Non-utf8 String in gix-date
    "RUSTSEC-2025-0021", # SHA-1 collision in gix-features
    "RUSTSEC-2021-0145", # atty potential unaligned read
    "RUSTSEC-2024-0375", # atty is unmaintained
    "RUSTSEC-2024-0436", # paste is unmaintained
    "RUSTSEC-2025-0119", # number_prefix is unmaintained
]

[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "Zlib",
    "0BSD",
    "Unicode-DFS-2016",
    "Unlicense",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "allow"

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
