// ignore_for_file: avoid-non-empty-constructor-bodies
import 'dart:ffi';

import 'package:ffi/ffi.dart';

import 'bindings.dart' as ffi;
import 'ffi_arena.dart';
import 'ffi_error.dart';
import 'ffi_result_unit.dart';

/// Owns a heap-allocated [FfiArena] AND every buffer hanging off it.
///
/// Life-cycle:
/// ```dart
///   final arena = FfiArenaHandle.allocate();
///   try {
///     ffi.some_call(..., arena.ptr, ...);
///   } finally {
///     arena.free();
///   }
/// ```
/// Do NOT pass [ptr] to code that outlives this handle — after [free] the
/// pointer is dangling and its memory is unmapped/reused.
final class FfiArenaHandle implements Finalizable {
  FfiArenaHandle._(this.ptr);

  /// Allocates an arena with an error buffer attached using Rust's allocator.
  factory FfiArenaHandle.allocate({int errorCapacity = defaultErrorCapacity}) {
    assert(errorCapacity > 0, 'errorCapacity must be positive');

    final arenaPtr = ffi.ffi_arena_create(errorCapacity);
    if (arenaPtr == nullptr) throw const OutOfMemoryError();

    final handle = FfiArenaHandle._(arenaPtr);

    _finalizer.attach(handle, arenaPtr.cast<Void>(), detach: handle);

    return handle;
  }

  /// Default error-buffer capacity. 512 bytes covers every error message
  /// currently generated by the Rust crate with room to spare.
  static const defaultErrorCapacity = 512;

  /// Pointer to the C-side struct. Pass to FFI calls as `arena.ptr`.
  final Pointer<FfiArena> ptr;

  static final _finalizer = NativeFinalizer(
    Native.addressOf<NativeFunction<Void Function(Pointer<FfiArena>)>>(
      ffi.ffi_arena_free,
    ).cast<NativeFinalizerFunction>(),
  );

  bool _isFreed = false;

  /// Reads the NUL-terminated UTF-8 message Rust wrote into `error.ptr`.
  /// Returns `null` if the buffer is missing, empty, or starts with NUL.
  String? get errorMessage {
    if (_isFreed) throw StateError('Cannot read from a freed FfiArenaHandle');

    final i = ptr.ref;
    final errorPointer = i.error.ptr;
    if (errorPointer == nullptr || i.error.len == 0) return null;
    // Check first byte: if 0, Rust didn't write anything (or wrote an empty string).
    if (errorPointer.value == 0) return null;

    return errorPointer.cast<Utf8>().toDartString();
  }

  /// Decodes a status code from Rust into a [FfiResultUnit] using this arena's error buffer.
  FfiResultUnit readResult(int code) {
    if (code == 0) return const OkUnit();
    final errorCode = FfiErrorCode.fromCode(code);

    return ErrUnit(errorCode, errorMessage ?? errorCode.description);
  }

  /// Frees the error buffer and the arena struct itself.
  void free() {
    if (_isFreed) return;
    _isFreed = true;

    _finalizer.detach(this);
    if (ptr != nullptr) ffi.ffi_arena_free(ptr);
  }
}
