//! FFI helper macros.
//!
//! Two macros:
//!  - `ffi_result!`  — declares a concrete `FfiResultXxx` enum for a given Ok type.
//!  - `ffi_export!`  — wraps an `unsafe extern "C"` fn body in `catch_unwind` and converts any `Result<T, FfiError>` / panic into the matching `FfiResultXxx`.
//!
//! `ffi_export!` requires the last parameter to be the arena pointer (any name works; it is
//! bound to `$arena` and forwarded to `write_panic_to_arena` on the panic path). The naming
//! convention keeps the generated code hygienic — the macro references `$arena` (the macro
//! variable) rather than a bare `arena` identifier, which would have definition-site hygiene
//! and silently resolve to a different symbol in the expanded code.

#[macro_export]
macro_rules! ffi_result {
    ($name:ident, $ok:ty) => {
        #[repr(C, u8)]
        pub enum $name {
            Ok($ok) = 0,
            Err($crate::ffi::FfiError) = 1,
        }

        impl $name {
            /// Convenience constructors so call sites read naturally.
            #[inline]
            pub fn ok(v: $ok) -> Self {
                Self::Ok(v)
            }
            #[inline]
            pub fn err(e: $crate::ffi::FfiError) -> Self {
                Self::Err(e)
            }
        }
    };
}

/// Wraps an `unsafe extern "C"` function body in `catch_unwind`.
///
/// Signature:
/// ```text
/// ffi_export! {
///     fn name(arg1: T1, arg2: T2; arena: *mut FfiArena) -> FfiResultXxx { body }
/// }
/// ```
///
/// The arena pointer **must** be the last argument, separated from the other args by `;`.
/// The `;` sentinel lets the macro unambiguously identify the arena parameter — `;` is in
/// the set of tokens allowed after a `ty` fragment, unlike `@` or bare commas which create
/// parse ambiguity with the greedy `$($arg:ident : $arg_ty:ty),*` repetition.
/// The generated function is `pub unsafe extern "C"` — FFI callers are responsible for
/// satisfying its preconditions.
#[macro_export]
macro_rules! ffi_export {
    (
        $(#[$meta:meta])*
        fn $name:ident (
            $($arg:ident : $arg_ty:ty),* $(,)?
            ; $arena:ident : $arena_ty:ty $(,)?
        ) -> $ret:ident $body:block
    ) => {
        $(#[$meta])*
        /// # Safety
        ///
        /// All pointer arguments must be valid for the duration of the call. This function is
        /// generated by `ffi_export!` and is intended to be called only from the Dart FFI layer.
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn $name( $($arg : $arg_ty ,)* $arena : $arena_ty ) -> $ret {
            let result = ::std::panic::catch_unwind(::std::panic::AssertUnwindSafe(|| {
                // Immediately-invoked closure so `?` propagates FfiError out of $body.
                let inner: ::std::result::Result<_, $crate::ffi::FfiError> = (|| $body)();
                inner
            }));

            match result {
                ::std::result::Result::Ok(::std::result::Result::Ok(v)) => <$ret>::ok(v),
                ::std::result::Result::Ok(::std::result::Result::Err(e)) => <$ret>::err(e),
                ::std::result::Result::Err(payload) => {
                    let msg = if let Some(s) = payload.downcast_ref::<&'static str>() {
                        (*s).to_string()
                    } else if let Some(s) = payload.downcast_ref::<::std::string::String>() {
                        s.clone()
                    } else {
                        "panic with non-string payload".to_string()
                    };
                    // SAFETY: `$arena` is the arena pointer from the function signature.
                    // The FFI caller (Dart) guarantees it is valid for the duration of the call.
                    let err = unsafe { $crate::ffi::write_panic_to_arena($arena, &msg) };
                    <$ret>::err(err)
                }
            }
        }
    };
}
