pub mod macros;

use std::ptr;

/// Error codes for FFI operations.
///
/// The numeric values **are part of the wire contract**: they are encoded in every
/// `FfiError.code` byte that crosses the FFI boundary. The Dart counterpart (`FfiErrorCode`)
/// must list variants in the same order. `u8` is sufficient — only 9 discriminants (0–8).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FfiErrorCode {
    Ok = 0,
    Panic = 1,
    InvalidArg = 2,
    Io = 3,
    Decode = 4,
    Encode = 5,
    Font = 6,
    Render = 7,
    Utf8 = 8,
}

/// A multi-buffer arena for passing variable-length data across FFI.
#[repr(C)]
pub struct FfiArena {
    pub text_buf: *const u8,
    pub text_len: usize,
    pub image_buf: *const u8,
    pub image_len: usize,
    pub error_buf: *mut u8,
    pub error_cap: usize,
}

/// A structured error returned from FFI.
///
/// Field sizes are chosen to be minimal:
/// - `code`: `u8` — only 9 discriminants (0–8); fits in one byte.
/// - `_pad`: alignment filler so `message_len` lands on a 2-byte boundary.
/// - `message_len`: `u16` — error message lengths up to 65 535 bytes; current arena cap is 256.
///
/// Total size: 4 bytes, alignment: 2.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct FfiError {
    pub code: u8,
    pub _pad: u8,
    pub message_len: u16,
}

impl FfiError {
    pub fn new(code: FfiErrorCode) -> Self {
        Self { code: code as u8, _pad: 0, message_len: 0 }
    }
}

const _: () = assert!(std::mem::size_of::<FfiError>() == 4);

/// Writes a panic message into the arena's error buffer and returns an FfiError.
///
/// # Safety `arena` must be a valid pointer to an `FfiArena`.
pub unsafe fn write_panic_to_arena(arena: *mut FfiArena, msg: &str) -> FfiError {
    write_error_to_arena(arena, FfiErrorCode::Panic, msg)
}

/// Writes a custom error message into the arena's error buffer.
///
/// If `arena` is null, or the arena has no error buffer, returns a bare `FfiError` with no
/// message. The function checks for null before dereferencing, so passing a null arena is safe.
// The raw pointer dereference is guarded by the `is_null()` check above; all callers are
// `unsafe extern "C"` entry points that guarantee arena validity.
#[allow(clippy::not_unsafe_ptr_arg_deref)]
pub fn write_error_to_arena(arena: *mut FfiArena, code: FfiErrorCode, msg: &str) -> FfiError {
    if arena.is_null() {
        return FfiError::new(code);
    }
    // SAFETY: we just checked `arena` is non-null. The caller (always an `unsafe extern "C"` fn
    // generated by `ffi_export!`) guarantees it is valid for the call duration.
    #[allow(clippy::not_unsafe_ptr_arg_deref)]
    let arena_ref = unsafe { &mut *arena };
    if arena_ref.error_buf.is_null() || arena_ref.error_cap == 0 {
        return FfiError::new(code);
    }

    let bytes = msg.as_bytes();
    let len = bytes.len().min(arena_ref.error_cap);
    unsafe {
        ptr::copy_nonoverlapping(bytes.as_ptr(), arena_ref.error_buf, len);
    }

    FfiError { code: code as u8, _pad: 0, message_len: len as u16 }
}
