pub mod macros;

use std::ptr;

/// Error codes for FFI operations.
///
/// The numeric values **are part of the wire contract**: they are encoded in every
/// `FfiError.code` byte that crosses the FFI boundary. The Dart counterpart (`FfiErrorCode`)
/// must list variants in the same order. `u8` is sufficient — only 9 discriminants (0–8).
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FfiErrorCode {
    Ok = 0,
    Panic = 1,
    InvalidArg = 2,
    Io = 3,
    Decode = 4,
    Encode = 5,
    Font = 6,
    Render = 7,
    Utf8 = 8,
}

/// A multi-buffer arena for passing variable-length data across FFI.
#[repr(C)]
pub struct FfiArena {
    pub text_buf: *const u8,
    pub text_len: usize,
    pub image_buf: *const u8,
    pub image_len: usize,
    pub error_buf: *mut u8,
    pub error_cap: usize,
}

/// A structured error returned from FFI.
///
/// Field sizes are chosen to be minimal:
/// - `code`: `u8` — only 9 discriminants (0–8); fits in one byte.
/// - `_pad`: alignment filler so `message_len` lands on a 2-byte boundary.
/// - `message_len`: `u16` — error message lengths up to 65 535 bytes; current arena cap is 256.
///
/// Total size: 4 bytes, alignment: 2.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct FfiError {
    pub code: u8,
    pub _pad: u8,
    pub message_len: u16,
}

impl FfiError {
    pub fn new(code: FfiErrorCode) -> Self {
        Self {
            code: code as u8,
            _pad: 0,
            message_len: 0,
        }
    }
}

const _: () = assert!(std::mem::size_of::<FfiError>() == 4);

/// Writes a panic message into the arena's error buffer and returns an FfiError.
///
/// # Safety `arena` must be a valid pointer to an `FfiArena`.
pub unsafe fn write_panic_to_arena(arena: *mut FfiArena, msg: &str) -> FfiError {
    unsafe { write_error_to_arena(arena, FfiErrorCode::Panic, msg) }
}

/// Writes a custom error message into the arena's error buffer.
///
/// If `arena` is null, or the arena has no error buffer, returns a bare `FfiError` with no
/// message.
///
/// # Safety
///
/// If `arena` is non-null, it must be a valid, aligned, dereferenceable `*mut FfiArena` for
/// the duration of the call. A null pointer is explicitly allowed and handled safely (no-op
/// message write, bare error returned).
// The raw pointer dereference is guarded by the `is_null()` check above; all callers are
// `unsafe extern "C"` entry points that guarantee arena validity.
pub unsafe fn write_error_to_arena(
    arena: *mut FfiArena,
    code: FfiErrorCode,
    msg: &str,
) -> FfiError {
    if arena.is_null() {
        return FfiError::new(code);
    }
    // SAFETY: we just checked `arena` is non-null. The caller (always an `unsafe extern "C"` fn
    // generated by `ffi_export!`) guarantees it is valid for the call duration.
    let arena_ref = unsafe { &mut *arena };
    if arena_ref.error_buf.is_null() || arena_ref.error_cap == 0 {
        return FfiError::new(code);
    }

    let bytes = msg.as_bytes();
    let limit = bytes.len().min(arena_ref.error_cap);
    // Guard: error_cap is stored as usize but message_len is u16. If cap ever exceeds
    // u16::MAX the cast below would silently truncate the length. Catch this in debug builds.
    debug_assert!(
        arena_ref.error_cap <= u16::MAX as usize,
        "error_cap {} exceeds u16::MAX",
        arena_ref.error_cap
    );
    // Clamp to the last valid UTF-8 boundary: a plain byte-count truncation can cut a
    // multi-byte codepoint in half, causing `utf8.decode` on the Dart side to throw a
    // FormatException. `valid_up_to()` gives us the byte index of the first invalid byte
    // after the longest valid prefix — always ≤ `limit`.
    let len = match std::str::from_utf8(&bytes[..limit]) {
        Ok(_) => limit,
        Err(e) => e.valid_up_to(),
    };
    unsafe {
        ptr::copy_nonoverlapping(bytes.as_ptr(), arena_ref.error_buf, len);
    }

    FfiError {
        code: code as u8,
        _pad: 0,
        message_len: len.min(u16::MAX as usize) as u16,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_arena(buf: &mut Vec<u8>) -> FfiArena {
        FfiArena {
            text_buf: std::ptr::null(),
            text_len: 0,
            image_buf: std::ptr::null(),
            image_len: 0,
            error_buf: buf.as_mut_ptr(),
            error_cap: buf.capacity(),
        }
    }

    // ── write_error_to_arena ──────────────────────────────────────────────────────────────────────

    #[test]
    fn write_error_null_arena_returns_bare_error() {
        let err =
            unsafe { write_error_to_arena(std::ptr::null_mut(), FfiErrorCode::Decode, "msg") };
        assert_eq!(err.code, FfiErrorCode::Decode as u8);
        assert_eq!(
            err.message_len, 0,
            "null arena must produce zero-length message"
        );
    }

    #[test]
    fn write_error_ascii_fits_exactly() {
        let mut buf = Vec::with_capacity(5);
        let mut arena = make_arena(&mut buf);
        let err = unsafe { write_error_to_arena(&mut arena, FfiErrorCode::Io, "hello") };
        assert_eq!(err.message_len, 5);
        unsafe { buf.set_len(5) };
        assert_eq!(std::str::from_utf8(&buf).unwrap(), "hello");
    }

    #[test]
    fn write_error_truncates_at_utf8_boundary_not_mid_codepoint() {
        // "aé" is 3 bytes: [0x61, 0xC3, 0xA9]. With cap=2 a naïve byte-count min
        // would write [0x61, 0xC3], which is invalid UTF-8 (orphaned leading byte).
        // The fixed code must write only [0x61] (1 byte) — the longest valid UTF-8 prefix.
        let mut buf = Vec::with_capacity(2);
        let mut arena = make_arena(&mut buf);
        let err = unsafe { write_error_to_arena(&mut arena, FfiErrorCode::Decode, "aé") };
        assert_eq!(
            err.message_len, 1,
            "must stop before the 2-byte 'é', not mid-codepoint"
        );
        unsafe { buf.set_len(1) };
        assert_eq!(std::str::from_utf8(&buf).unwrap(), "a");
    }

    #[test]
    fn write_error_multibyte_fits_completely() {
        // "éàü" is 6 bytes; with cap=6 all three codepoints must be written intact.
        let mut buf = Vec::with_capacity(6);
        let mut arena = make_arena(&mut buf);
        let err = unsafe { write_error_to_arena(&mut arena, FfiErrorCode::Font, "éàü") };
        assert_eq!(err.message_len, 6);
        unsafe { buf.set_len(6) };
        assert_eq!(std::str::from_utf8(&buf).unwrap(), "éàü");
    }

    #[test]
    fn write_error_four_byte_codepoint_truncated_cleanly() {
        // '𝄞' (MUSICAL SYMBOL G CLEF) is 4 bytes (U+1D11E). With cap=3, nothing should be
        // written — even 3 bytes would be an incomplete codepoint.
        let mut buf = Vec::with_capacity(3);
        let mut arena = make_arena(&mut buf);
        let err = unsafe { write_error_to_arena(&mut arena, FfiErrorCode::Render, "𝄞") };
        assert_eq!(
            err.message_len, 0,
            "4-byte codepoint must not be written into a 3-byte buffer"
        );
    }
}
