version: 0.0.1+0
name: frigatedraw_example
description: "Demonstrates how to use the frigatedraw package."
publish_to: none

resolution: workspace

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  frigatedraw:
    path: ../
  meta: any # Constrained by Flutter SDK
  path_provider_dart:
    git: https://github.com/tsinis/path_provider

dev_dependencies:
  dart_code_metrics_presets: any # Constrained in the workspace pubspec.yaml
  flutter_lints: any # Constrained in the parent pubspec.yaml

flutter:
  uses-material-design: true
  config:
    enable-swift-package-manager: true

  assets:
    - assets/sample.png
    - assets/RobotoMono.ttf
